/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComoAvaliamosRouteImport } from './routes/como-avaliamos'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AfiliadosRouteImport } from './routes/afiliados'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewSlugRouteImport } from './routes/review.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'

const ComoAvaliamosRoute = ComoAvaliamosRouteImport.update({
  id: '/como-avaliamos',
  path: '/como-avaliamos',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosRoute = AfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewSlugRoute = ReviewSlugRouteImport.update({
  id: '/review/$slug',
  path: '/review/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afiliados': typeof AfiliadosRoute
  '/busca': typeof BuscaRoute
  '/como-avaliamos': typeof ComoAvaliamosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afiliados': typeof AfiliadosRoute
  '/busca': typeof BuscaRoute
  '/como-avaliamos': typeof ComoAvaliamosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/afiliados': typeof AfiliadosRoute
  '/busca': typeof BuscaRoute
  '/como-avaliamos': typeof ComoAvaliamosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afiliados'
    | '/busca'
    | '/como-avaliamos'
    | '/categoria/$slug'
    | '/review/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afiliados'
    | '/busca'
    | '/como-avaliamos'
    | '/categoria/$slug'
    | '/review/$slug'
  id:
    | '__root__'
    | '/'
    | '/afiliados'
    | '/busca'
    | '/como-avaliamos'
    | '/categoria/$slug'
    | '/review/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AfiliadosRoute: typeof AfiliadosRoute
  BuscaRoute: typeof BuscaRoute
  ComoAvaliamosRoute: typeof ComoAvaliamosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ReviewSlugRoute: typeof ReviewSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/como-avaliamos': {
      id: '/como-avaliamos'
      path: '/como-avaliamos'
      fullPath: '/como-avaliamos'
      preLoaderRoute: typeof ComoAvaliamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados': {
      id: '/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$slug': {
      id: '/review/$slug'
      path: '/review/$slug'
      fullPath: '/review/$slug'
      preLoaderRoute: typeof ReviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AfiliadosRoute: AfiliadosRoute,
  BuscaRoute: BuscaRoute,
  ComoAvaliamosRoute: ComoAvaliamosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ReviewSlugRoute: ReviewSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
