/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComoAvaliamosRouteImport } from './routes/como-avaliamos'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AfiliadosRouteImport } from './routes/afiliados'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ReviewSlugRouteImport } from './routes/review.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const ComoAvaliamosRoute = ComoAvaliamosRouteImport.update({
  id: '/como-avaliamos',
  path: '/como-avaliamos',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosRoute = AfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ReviewSlugRoute = ReviewSlugRouteImport.update({
  id: '/review/$slug',
  path: '/review/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/afiliados': typeof AfiliadosRoute
  '/busca': typeof BuscaRoute
  '/como-avaliamos': typeof ComoAvaliamosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/posts': typeof AdminPostsRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afiliados': typeof AfiliadosRoute
  '/busca': typeof BuscaRoute
  '/como-avaliamos': typeof ComoAvaliamosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/posts': typeof AdminPostsRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/afiliados': typeof AfiliadosRoute
  '/busca': typeof BuscaRoute
  '/como-avaliamos': typeof ComoAvaliamosRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/posts': typeof AdminPostsRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/review/$slug': typeof ReviewSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/afiliados'
    | '/busca'
    | '/como-avaliamos'
    | '/admin/login'
    | '/admin/posts'
    | '/categoria/$slug'
    | '/review/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afiliados'
    | '/busca'
    | '/como-avaliamos'
    | '/admin/login'
    | '/admin/posts'
    | '/categoria/$slug'
    | '/review/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/afiliados'
    | '/busca'
    | '/como-avaliamos'
    | '/admin/login'
    | '/admin/posts'
    | '/categoria/$slug'
    | '/review/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AfiliadosRoute: typeof AfiliadosRoute
  BuscaRoute: typeof BuscaRoute
  ComoAvaliamosRoute: typeof ComoAvaliamosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ReviewSlugRoute: typeof ReviewSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/como-avaliamos': {
      id: '/como-avaliamos'
      path: '/como-avaliamos'
      fullPath: '/como-avaliamos'
      preLoaderRoute: typeof ComoAvaliamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados': {
      id: '/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/review/$slug': {
      id: '/review/$slug'
      path: '/review/$slug'
      fullPath: '/review/$slug'
      preLoaderRoute: typeof ReviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AfiliadosRoute: AfiliadosRoute,
  BuscaRoute: BuscaRoute,
  ComoAvaliamosRoute: ComoAvaliamosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ReviewSlugRoute: ReviewSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
