// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqittiosnjiwfwbdcypu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxaXR0aW9zbmppd2Z3YmRjeXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyNTM2NzAsImV4cCI6MjA5NDgyOTY3MH0.GzSismuZDI82nJ0OdKTYKRGpsgWko_z7lE-05xbTR2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});