// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Blindagem: valores reais do projeto como fallback hardcoded.
// Nunca mais usar "placeholder-*" — ele mascara falhas de env e leva
// a "sumiço de dados" silencioso depois de rebuilds.
const REAL_SUPABASE_URL = "https://sqittiosnjiwfwbdcypu.supabase.co";
const REAL_SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxaXR0aW9zbmppd2Z3YmRjeXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkyNTM2NzAsImV4cCI6MjA5NDgyOTY3MH0.GzSismuZDI82nJ0OdKTYKRGpsgWko_z7lE-05xbTR2I";

const envUrl =
  import.meta.env.VITE_SUPABASE_URL ||
  import.meta.env.SUPABASE_URL ||
  import.meta.env.NEXT_PUBLIC_SUPABASE_URL;
const envKey =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.SUPABASE_ANON_KEY ||
  import.meta.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

const isValidUrl =
  typeof envUrl === "string" &&
  envUrl.startsWith("https://") &&
  !envUrl.includes("placeholder") &&
  envUrl.includes(".supabase.co");
const isValidKey =
  typeof envKey === "string" &&
  envKey.length > 40 &&
  !envKey.includes("placeholder");

const SUPABASE_URL = isValidUrl ? envUrl! : REAL_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = isValidKey ? envKey! : REAL_SUPABASE_PUBLISHABLE_KEY;

if (!isValidUrl || !isValidKey) {
  // Fail-loud: queremos ver isso nos logs se as envs do build sumirem.
  console.error(
    "[supabase/client] VITE_SUPABASE_* ausentes ou inválidas — usando fallback hardcoded do projeto real. Verifique o .env do deploy.",
    { envUrlPresent: !!envUrl, envKeyPresent: !!envKey },
  );
}

// Sanity check do project ref para impedir regressão silenciosa.
if (!SUPABASE_URL.includes("sqittiosnjiwfwbdcypu")) {
  console.error(
    "[supabase/client] URL não corresponde ao project ref esperado (sqittiosnjiwfwbdcypu):",
    SUPABASE_URL,
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});